### ISSUE TITLE
Can't reopen the installer after mini installation

### ISSUE THREAD

**Issue by arukateru** [AdvDebug/NoMoreCookies#15] opened 2023-10-15 18:30 UTC
Hi, wonderful work, this is a revolutionary program! However, there is a bug where you can not reopen the installer after installation. I tried installing all the versions, and the bug happened to me after installing the mini version. I also tried with enabling secure boot and trying to rerun the installer in case the AppinitDLL being loaded was causing a problem, without success. Translation of the top text: "Attempt to read or write in protected memory. Often, this indicates that there is other damaged memory." Also, I don't know about its support on Windows 7, but this is Windows 10 (LTSC 2019 aka 1809) modified to look like Windows 7.

![screenshotbug](https://github.com/AdvDebug/NoMoreCookies/assets/84914212/f2afea09-9787-4213-bac1-92194cf3fe7f)

**Comment by AdvDebug** [comment] 2023-10-15 19:31
Hi, firstly i would like to thank you for your comment, i try my best to make this program work well altho i know it's not enough and there's some methods which can be used for bypassing the program, but i'm moving to encrypting the profiles folder in addition to preventing access so the next update may take a long time. and about your issue, i can't reproduce the problem to know the exact issue, and the problem is that NoMoreCookies doesn't do anything to the installer as the installer is whitelisted by NoMoreCookies, so i would recommend just turning off updates checking by modifying the source, but that would also mean the dlls would not identify the installer anymore as the hash changed, but in the next update i may add an option to ignore checking for updates (or even ignore warnings) and making the installer more customizable in general.

so i would say just try to uninstall the program by using a version that doesn't have updates checking, like this [one](https://github.com/AdvDebug/NoMoreCookies/releases/tag/NoMoreCookies_1.8).

**Closed** 2023-10-31 02:11 UTC
